version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      # release-please considers "deps:" as a releasable unit
      prefix: "deps:"
    schedule:
      interval: weekly
