name: Mix Compile
description: Compile an Elixir project

inputs:
  mix-env:
    description: MIX_ENV to compile with
    required: true
  args:
    description: Additional arguments to pass to mix compile
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Compile
      shell: bash
      run: mix compile ${{ inputs.args }}
      env:
        MIX_ENV: ${{ inputs.mix-env }}
