name: Mix Compile
description: Compile an Elixir project

inputs:
  mix-env:
    description: MIX_ENV to compile with
    required: true
  args:
    description: Additional arguments to pass to mix compile
    required: false
    default: ""
  directory:
    description: Directory containing the Elixir project
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Compile
      shell: bash
      working-directory: ${{ inputs.directory }}
      env:
        MIX_ENV: ${{ inputs.mix-env }}
        COMPILE_ARGS: ${{ inputs.args }}
      run: mix compile ${COMPILE_ARGS}
