name: Install APT Packages
description: Install system packages via apt-get

inputs:
  packages:
    description: Space or newline separated list of packages to install
    required: true

runs:
  using: composite
  steps:
    - name: Install APT packages
      shell: bash
      env:
        PACKAGES: ${{ inputs.packages }}
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ${PACKAGES}
